# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the frequency matrix for Signal Detection Theory (C++ core)
#'
#' @param stim The numeric vector indicating the signal type.
#' @param resp The numeric vector indicating the decision or response.
#' @param conf The numeric vector indicating the confidence level (optional).
#' @import Rcpp
#' @export
matrix_freq <- function(stim, resp, conf = NULL) {
    .Call(`_metaSDT_matrix_freq`, stim, resp, conf)
}

