# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate Model Likelihood indicators (NLL, AIC, BIC)
#' @export
criterion_likelihood <- function(freq_mat, prob_mat, std_params) {
    .Call(`_metaSDT_r_criterion_likelihood`, freq_mat, prob_mat, std_params)
}

#' Evaluate Log-Posterior
#' @export
criterion_posterior <- function(freq_mat, user_priors, std_params = NULL) {
    .Call(`_metaSDT_r_criterion_posterior`, freq_mat, user_priors, std_params)
}

#' Evaluate Log-Prior
#' @export
criterion_prior <- function(user_priors, std_params = NULL) {
    .Call(`_metaSDT_r_criterion_prior`, user_priors, std_params)
}

#' Intelligently scan the dataset and extract subject-level information.
data_info <- function(df, colnames = NULL) {
    .Call(`_metaSDT_r_data_info`, df, colnames)
}

#' Perform Maximum Likelihood Estimation (MLE) for metaSDT models
#'
#' @description
#' Multi-threaded optimization using NLOPT to find the best fitting parameters 
#' for each subject independently.
#' 
#' @param df The dataset as a data.frame.
#' @param colnames A list mapping standard roles (stim, resp, conf, etc.) to your column names.
#' @param params A list of user-defined parameters (free, fixed, constant).
#' @param model_name The name of the model to fit (e.g., "sdt").
#' 
#' @return A data.frame of fitting results for each subject.
#' @import Rcpp
#' @import nloptr
#' @export
estimate_mle <- function(df, colnames = NULL, params = NULL, model = "sdt", control = NULL, lower = NULL, upper = NULL) {
    .Call(`_metaSDT_r_estimate_mle`, df, colnames, params, model, control, lower, upper)
}

#' Calculate the frequency matrix for Signal Detection Theory (C++ core)
#'
#' @param stim The numeric vector indicating the signal type.
#' @param resp The numeric vector indicating the decision or response.
#' @param conf The numeric vector indicating the confidence level (optional).
#' @param diff The numeric vector indicating the difficulty level (optional).
#' @import Rcpp
#' @export
matrix_freq <- function(stim, resp, conf = NULL, diff = NULL) {
    .Call(`_metaSDT_r_matrix_freq`, stim, resp, conf, diff)
}

#' Calculate the Log-Likelihood product matrix
#' @export
matrix_mult <- function(freq_mat, prob_mat, std_params) {
    .Call(`_metaSDT_r_matrix_mult`, freq_mat, prob_mat, std_params)
}

#' Calculate Probability Matrix
matrix_prob <- function(cdf_noise, cdf_signal, params) {
    .Call(`_metaSDT_r_matrix_prob`, cdf_noise, cdf_signal, params)
}

model_sdt <- function(params) {
    .Call(`_metaSDT_r_model_sdt`, params)
}

#' Modify and flatten model parameters (C++ core)
#'
#' @description
#' A robust function to manage model parameters. It takes user-defined parameters,
#' merges them with a set of defaults, resolves any conflicts based on a
#' `free > fixed > constant` priority, and returns a single flattened list.
#'
#' @param params A list or a named vector specifying user parameters.
#'   - If `params` is a list containing `free`, `fixed`, or `constant` slots,
#'     it's treated as a structured parameter set.
#'   - If `params` is a simple named list (e.g., `list(d=2)`) or a named vector
#'     (e.g., `c(d=2)`), all its elements are treated as **free** parameters by default.
#'   - If `params` is empty or `NULL`, the function returns the default flattened parameter set.
#'
#' @return A named list containing the final, flattened parameters.
#' @import Rcpp
#' @export
modify_params <- function(user_params = NULL) {
    .Call(`_metaSDT_r_modify_params`, user_params)
}

#' Modify and align prior distributions
#' @export
modify_prior <- function(user_priors, std_params = NULL) {
    .Call(`_metaSDT_r_modify_prior`, user_priors, std_params)
}

