// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// r_criterion_likelihood
Rcpp::List r_criterion_likelihood(Rcpp::List freq_mat, Rcpp::List prob_mat, Rcpp::List std_params);
RcppExport SEXP _metaSDT_r_criterion_likelihood(SEXP freq_matSEXP, SEXP prob_matSEXP, SEXP std_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type freq_mat(freq_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type prob_mat(prob_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type std_params(std_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(r_criterion_likelihood(freq_mat, prob_mat, std_params));
    return rcpp_result_gen;
END_RCPP
}
// r_criterion_posterior
double r_criterion_posterior(Rcpp::List freq_mat, Rcpp::List user_priors, Rcpp::RObject std_params);
RcppExport SEXP _metaSDT_r_criterion_posterior(SEXP freq_matSEXP, SEXP user_priorsSEXP, SEXP std_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type freq_mat(freq_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type user_priors(user_priorsSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type std_params(std_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(r_criterion_posterior(freq_mat, user_priors, std_params));
    return rcpp_result_gen;
END_RCPP
}
// r_criterion_prior
double r_criterion_prior(Rcpp::List user_priors, Rcpp::RObject std_params);
RcppExport SEXP _metaSDT_r_criterion_prior(SEXP user_priorsSEXP, SEXP std_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type user_priors(user_priorsSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type std_params(std_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(r_criterion_prior(user_priors, std_params));
    return rcpp_result_gen;
END_RCPP
}
// r_data_info
Rcpp::List r_data_info(Rcpp::DataFrame df, Rcpp::Nullable<Rcpp::List> colnames);
RcppExport SEXP _metaSDT_r_data_info(SEXP dfSEXP, SEXP colnamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type colnames(colnamesSEXP);
    rcpp_result_gen = Rcpp::wrap(r_data_info(df, colnames));
    return rcpp_result_gen;
END_RCPP
}
// r_estimate_map
Rcpp::RObject r_estimate_map(Rcpp::DataFrame df, Rcpp::Nullable<Rcpp::List> colnames, Rcpp::Nullable<Rcpp::RObject> params, std::string model, Rcpp::Nullable<Rcpp::List> control, Rcpp::Nullable<Rcpp::List> lower, Rcpp::Nullable<Rcpp::List> upper, Rcpp::Nullable<Rcpp::List> user_priors);
RcppExport SEXP _metaSDT_r_estimate_map(SEXP dfSEXP, SEXP colnamesSEXP, SEXP paramsSEXP, SEXP modelSEXP, SEXP controlSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP user_priorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type colnames(colnamesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::RObject> >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< std::string >::type model(modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type control(controlSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type user_priors(user_priorsSEXP);
    rcpp_result_gen = Rcpp::wrap(r_estimate_map(df, colnames, params, model, control, lower, upper, user_priors));
    return rcpp_result_gen;
END_RCPP
}
// r_estimate_mle
Rcpp::RObject r_estimate_mle(Rcpp::DataFrame df, Rcpp::Nullable<Rcpp::List> colnames, Rcpp::Nullable<Rcpp::RObject> params, std::string model, Rcpp::Nullable<Rcpp::List> control, Rcpp::Nullable<Rcpp::List> lower, Rcpp::Nullable<Rcpp::List> upper);
RcppExport SEXP _metaSDT_r_estimate_mle(SEXP dfSEXP, SEXP colnamesSEXP, SEXP paramsSEXP, SEXP modelSEXP, SEXP controlSEXP, SEXP lowerSEXP, SEXP upperSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::DataFrame >::type df(dfSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type colnames(colnamesSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::RObject> >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< std::string >::type model(modelSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type control(controlSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::List> >::type upper(upperSEXP);
    rcpp_result_gen = Rcpp::wrap(r_estimate_mle(df, colnames, params, model, control, lower, upper));
    return rcpp_result_gen;
END_RCPP
}
// r_matrix_freq
Rcpp::List r_matrix_freq(Rcpp::NumericVector stim, Rcpp::NumericVector resp, Rcpp::Nullable<Rcpp::NumericVector> conf, Rcpp::Nullable<Rcpp::NumericVector> diff);
RcppExport SEXP _metaSDT_r_matrix_freq(SEXP stimSEXP, SEXP respSEXP, SEXP confSEXP, SEXP diffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type stim(stimSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type resp(respSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type conf(confSEXP);
    Rcpp::traits::input_parameter< Rcpp::Nullable<Rcpp::NumericVector> >::type diff(diffSEXP);
    rcpp_result_gen = Rcpp::wrap(r_matrix_freq(stim, resp, conf, diff));
    return rcpp_result_gen;
END_RCPP
}
// r_matrix_mult
Rcpp::List r_matrix_mult(Rcpp::List freq_mat, Rcpp::List prob_mat, Rcpp::List std_params);
RcppExport SEXP _metaSDT_r_matrix_mult(SEXP freq_matSEXP, SEXP prob_matSEXP, SEXP std_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type freq_mat(freq_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type prob_mat(prob_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type std_params(std_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(r_matrix_mult(freq_mat, prob_mat, std_params));
    return rcpp_result_gen;
END_RCPP
}
// r_matrix_prob
Rcpp::List r_matrix_prob(Rcpp::List cdf_noise, Rcpp::List cdf_signal, Rcpp::List params);
RcppExport SEXP _metaSDT_r_matrix_prob(SEXP cdf_noiseSEXP, SEXP cdf_signalSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type cdf_noise(cdf_noiseSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type cdf_signal(cdf_signalSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(r_matrix_prob(cdf_noise, cdf_signal, params));
    return rcpp_result_gen;
END_RCPP
}
// r_model_sdt
Rcpp::List r_model_sdt(Rcpp::List params);
RcppExport SEXP _metaSDT_r_model_sdt(SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(r_model_sdt(params));
    return rcpp_result_gen;
END_RCPP
}
// r_modify_params
Rcpp::List r_modify_params(Rcpp::RObject user_params);
RcppExport SEXP _metaSDT_r_modify_params(SEXP user_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::RObject >::type user_params(user_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(r_modify_params(user_params));
    return rcpp_result_gen;
END_RCPP
}
// r_modify_prior
Rcpp::List r_modify_prior(Rcpp::List user_priors, Rcpp::RObject std_params);
RcppExport SEXP _metaSDT_r_modify_prior(SEXP user_priorsSEXP, SEXP std_paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::List >::type user_priors(user_priorsSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type std_params(std_paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(r_modify_prior(user_priors, std_params));
    return rcpp_result_gen;
END_RCPP
}
// r_progress_start
void r_progress_start(double total, std::string title, int refresh_ms, std::string mode, double line_interval_sec, double line_interval_pct);
RcppExport SEXP _metaSDT_r_progress_start(SEXP totalSEXP, SEXP titleSEXP, SEXP refresh_msSEXP, SEXP modeSEXP, SEXP line_interval_secSEXP, SEXP line_interval_pctSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type total(totalSEXP);
    Rcpp::traits::input_parameter< std::string >::type title(titleSEXP);
    Rcpp::traits::input_parameter< int >::type refresh_ms(refresh_msSEXP);
    Rcpp::traits::input_parameter< std::string >::type mode(modeSEXP);
    Rcpp::traits::input_parameter< double >::type line_interval_sec(line_interval_secSEXP);
    Rcpp::traits::input_parameter< double >::type line_interval_pct(line_interval_pctSEXP);
    r_progress_start(total, title, refresh_ms, mode, line_interval_sec, line_interval_pct);
    return R_NilValue;
END_RCPP
}
// r_progress_set
void r_progress_set(double current);
RcppExport SEXP _metaSDT_r_progress_set(SEXP currentSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type current(currentSEXP);
    r_progress_set(current);
    return R_NilValue;
END_RCPP
}
// r_progress_advance
void r_progress_advance(double step);
RcppExport SEXP _metaSDT_r_progress_advance(SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type step(stepSEXP);
    r_progress_advance(step);
    return R_NilValue;
END_RCPP
}
// r_progress_finish
void r_progress_finish();
RcppExport SEXP _metaSDT_r_progress_finish() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    r_progress_finish();
    return R_NilValue;
END_RCPP
}
// r_progress_snapshot
Rcpp::List r_progress_snapshot();
RcppExport SEXP _metaSDT_r_progress_snapshot() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(r_progress_snapshot());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_metaSDT_r_criterion_likelihood", (DL_FUNC) &_metaSDT_r_criterion_likelihood, 3},
    {"_metaSDT_r_criterion_posterior", (DL_FUNC) &_metaSDT_r_criterion_posterior, 3},
    {"_metaSDT_r_criterion_prior", (DL_FUNC) &_metaSDT_r_criterion_prior, 2},
    {"_metaSDT_r_data_info", (DL_FUNC) &_metaSDT_r_data_info, 2},
    {"_metaSDT_r_estimate_map", (DL_FUNC) &_metaSDT_r_estimate_map, 8},
    {"_metaSDT_r_estimate_mle", (DL_FUNC) &_metaSDT_r_estimate_mle, 7},
    {"_metaSDT_r_matrix_freq", (DL_FUNC) &_metaSDT_r_matrix_freq, 4},
    {"_metaSDT_r_matrix_mult", (DL_FUNC) &_metaSDT_r_matrix_mult, 3},
    {"_metaSDT_r_matrix_prob", (DL_FUNC) &_metaSDT_r_matrix_prob, 3},
    {"_metaSDT_r_model_sdt", (DL_FUNC) &_metaSDT_r_model_sdt, 1},
    {"_metaSDT_r_modify_params", (DL_FUNC) &_metaSDT_r_modify_params, 1},
    {"_metaSDT_r_modify_prior", (DL_FUNC) &_metaSDT_r_modify_prior, 2},
    {"_metaSDT_r_progress_start", (DL_FUNC) &_metaSDT_r_progress_start, 6},
    {"_metaSDT_r_progress_set", (DL_FUNC) &_metaSDT_r_progress_set, 1},
    {"_metaSDT_r_progress_advance", (DL_FUNC) &_metaSDT_r_progress_advance, 1},
    {"_metaSDT_r_progress_finish", (DL_FUNC) &_metaSDT_r_progress_finish, 0},
    {"_metaSDT_r_progress_snapshot", (DL_FUNC) &_metaSDT_r_progress_snapshot, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_metaSDT(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
